services:
  devDB:
    image: mysql
    ports:
      - ${DEV_DATABASE_PORT}:3306
    volumes:
      - ./localdb/dev_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DEV_DATABASE_NAME}

  prodDB:
    image: mysql
    ports:
      - ${PROD_DATABASE_PORT}:3306
    volumes:
      - ./localdb/prod_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${PROD_DATABASE_NAME}
